---
- name: Add piHole user
  user:
    name: "{{ pihole_user_name }}"
    system: yes
    shell: /usr/sbin/nologin
    comment: 'piHole User'
    append: yes
    state: present

- name: create pihole directory
  file:
    path: "{{ pihole_working_directory }}"
    state: directory
    owner: "{{ pihole_user_name }}"
    group: "{{ pihole_user_group }}"
  when: pihole_installed

- name: "Configure piHole Settings"
  template:
    src: setupVars.conf.j2
    dest: "{{ pihole_working_directory }}/setupVars.conf"
  when: pihole_installed
  tags:
    - pihole-config

- name: "Configure piHole Adlists"
  template:
    src: adlists.list.j2
    dest: "{{ pihole_working_directory }}/adlists.list"
  when: pihole_installed
  tags:
    - adlist
  notify:
    - pihole gravity
