---
## setup the directories
- name: Create LigHTTPD directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pihole_lighttpd_user }}"
    group: "{{ pihole_lighttpd_user }}"
  with_items:
    - /var/run/lighttpd
    - /var/run/compress
    - /var/run/uploads

- name: Create www html folder
  file:
    path: "/var/www/html"
    state: directory
    owner: "{{ pihole_lighttpd_user }}"
    group: "{{ pihole_lighttpd_user }}"
    mode: 0755

## Handle copying of the config
- name: Ensure External Config Exists
  copy:
    content: ""
    dest: "{{ pihole_lighttpd_external_file }}"
    force: no
    group: root
    owner: root
    mode: 0644

- name: Copy LigHTTPD config
  copy:
    src: "{{ pihole_repo_dir }}/advanced/{{ pihole_lighttpd_config_file }}"
    dest: "{{ pihole_lighttpd_config_dest }}"
    remote_src: true
    mode: 0644
    backup: true
    owner: "{{ pihole_lighttpd_user }}"
    group: "{{ pihole_lighttpd_user }}"
  notify:
    - restart lighttpd

- name: Enable LigHTTPD Modules
  # shell: "{{ pihole_lighttpd_mod_manager }} fastcgi fastcgi-php"
  shell: "{{ pihole_lighttpd_mod_manager }} fastcgi fastcgi-php > /dev/null"
  ignore_errors: yes
  when:
    - pihole_lighttpd_enable_modules

    # # Install the directory
    # install -d /var/www/html/pihole
- name: Create piHole Web Directory
  file:
    path: "{{ pihole_lighttpd_blocked_path }}"
    state: directory
    owner: "{{ pihole_lighttpd_user }}"
    group: "{{ pihole_lighttpd_user }}"
    mode: 0755

## TODO come back and paramitise the index and block files
- name: "Copy Block Page"
  copy:
    src: "{{ item }}"
    dest: "{{ pihole_lighttpd_blocked_path }}"
    remote_src: true
    mode: 0644
    owner: "{{ pihole_lighttpd_user }}"
    group: "{{ pihole_lighttpd_user }}"
  with_items:
    - "{{ pihole_repo_dir }}/advanced/index.php"
    - "{{ pihole_repo_dir }}/advanced/blockingpage.css"

- name: Remove superseded file
  file:
    path: "/var/www/html/pihole/index.js"
    state: absent

- name: "Copy Default Pages Page"
  copy:
    src: "{{ item }}"
    dest: "{{ pihole_lighttpd_blocked_path }}"
    remote_src: true
    mode: 0644
    owner: "{{ pihole_lighttpd_user }}"
    group: "{{ pihole_lighttpd_user }}"
  with_items:
    - "{{ pihole_repo_dir }}/advanced/index.php"
    - "{{ pihole_repo_dir }}/advanced/blockingpage.css"

    # command: touch example{{ansible_date_time.date}}.log

- name: "Make backups of Default Pages"
  copy:
    src: "{{ item }}"
    dest: "{{ item }}-{{ ansible_date_time.date }}.old"
    remote_src: true
  with_items: "{{ pihole_remove_pages }}"

- name: Remove Default files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ pihole_remove_pages }}"
