---
## Gather Facts
- name: Fact Gathering
  include: facts.yml
  tags:
    - always


- name: Clone Repositories
  include: pihole_repos.yml
  tags:
    - pihole-install
    - pihole-repositories

## TODO preflight check for supported OS's
## ansible_distribution_major_version = 7 for centos, all debian bases seem
## to be supported

- name: Install Required Packages
  include: package_install.yml
  tags:
    - pihole-install-requirements

- name: Install Required Packages
  include: lighttpd_configure.yml
  tags:
    - pihole-install-requirements
    - special

- name: Install PiHole
  include: pihole_install.yml
  tags:
    - pihole-install

## TODO - Handle firewall rules

- debug:
    msg: "Pihole does not appear to be installed, you should run the installer"
  when: not pihole_installed

- name: Install PiHole Extras
  include: pihole_extra.yml
  tags:
    - pihole-extra

## no-op to restart services when it's installed?
## TODO decide on whether to remove or not
- name: "Restarting Pihole services"
  command: /bin/true
  when: pihole_installed
  notify:
    - restart pihole
    - restart lighttpd
