---
## Gather Facts
- name: Fact Gathering
  include: facts.yml
  tags:
    - pihole-config
    - pihole-install-requirements

## TODO preflight check for supported OS's
## ansible_distribution_major_version = 7 for centos, all debian bases seem
## to be supported

- name: Install Required Packages
  include: package_install.yml
  tags:
    - pihole-install-requirements

- name: Clone Repositories
  include: pihole_repos.yml
  tags:
    - pihole-install
    - pihole-repositories

- name: Install PiHole
  include: pihole_install.yml
  tags:
    - pihole-install

## TODO release is based off of hash of the install script - so we can detect changes
# - name: Download Install Script
#   get_url:
#     url: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
#     dest: "{{ ansible_user_dir }}/pihole-install.sh"
#     mode: u+rwx
#   when: not pihole_installed

## TODO - Handle firewall rules

- debug:
    msg: "Pihole does not appear to be installed, you should run the installer"
  when: not pihole_installed

- name: Bandage DHCPD Config (regardless of state)
  blockinfile:
    path: "{{ dhcpd_config_file }}"
    block: |
      interface {{ pihole_listen_interface }}
      static ip_address={{ pihole_listen_address_ipv4 }}
      static routers={{ pihole_gateway_ipv4 }}
      static domain_name_servers=127.0.0.1
    marker: "# {{ ansible_managed }} "
  when: dhcpd_config_present

- name: "Making sure DHCP client is disabled"
  command: /bin/true
  notify:
    - stop dhcp client
  when: dhcpd_service_present

## no-op to restart services when it's installed?
## TODO decide on whether to remove or not
- name: "Restarting Pihole services"
  command: /bin/true
  when: pihole_installed
  notify:
    - restart pihole
    - restart lighttpd
