---
- name: "Clean Apt Cache"
  apt:
    autoclean: yes
    autoremove: yes
  when:
    - ansible_pkg_mgr == 'apt'

- name: 'Add PHP 7 Repo to Debian'
  apt_repository:
    repo: "deb http://packages.dotdeb.org {{ ansible_distribution_release }} all"
    state: present
    filename: php-7-dotdeb
  when:
    - ansible_pkg_mgr == 'apt'

- name: 'Add PHP 7 Repo KEY to Debian'
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present
  when:
    - ansible_pkg_mgr == 'apt'

- name: Upate APT Cache
  apt:
    update_cache: yes
  when:
    - ansible_pkg_mgr == 'apt'

- name: Upate Yum Cache
  yum:
    ## Can't update yum packages without a name command :(
    name: curl
    state: present
    update_cache: yes
  when:
    - ansible_pkg_mgr == 'yum'

- name: Remove conflicting packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
      - apache2
      - apache2ctl
      - apachectl

# Seperate to make debugging steps easier, it takes a little longer though
- name: Install Common Core Requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - bc
      - curl
      - sudo
      - unzip
      - wget
      - sqlite3
      - lighttpd

- name: Install iproute/iproute2
  package:
    name: "{{ pihole_iproute_package_name }}"
    state: present

- name: Install Debian Core Requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
       - cron
       - dnsutils
       - iputils-ping
       - lsof
       - netcat
       - psmisc
       - idn2
       - libcap2-bin
       - dns-root-data
       - resolvconf
  when: ansible_os_family == 'Debian'

- name: Install CentOS/Redhat Core Requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - bind-utils
      - cronie
      - findutils
      - nmap-ncat
      - libidn2
      - psmisc
  when: ansible_os_family == 'RedHat'

- name: Install web requirements (Default PHP)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-sqlite3
    - php-common
    - php-cgi
    - php-json
  state: present
  when:
    - can_install_php.rc == 0
    - can_install_sqlite3.rc == 0
    - ansible_os_family == 'Debian'


## Light https fastcgi needs to be handlged Line 1774
# php7.0-x
