---

- name: 'Make sure directories exists'
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pihole_user_name }}"
    group: "{{ pihole_user_group }}"
    recurse: yes
  with_items:
    - /var/run/pihole
    - /var/log/pihole

- name: 'Touch needed files'
  file:
    path: "{{ item }}"
    state: touch
    owner: "{{ pihole_user_name }}"
    group: "{{ pihole_user_group }}"
  with_items:
    - /var/log/pihole-FTL.log
    - /var/log/pihole.log
    - /run/pihole-FTL.pid
    - /run/pihole-FTL.port
    - /etc/pihole/dhcp.leases

- name: Install pihole-FTL Service (systemd)
  template:
    src: pihole-FTL.service.j2
    dest: "/etc/systemd/system/pihole-FTL.service"
  tags:
    - pihole-service

## Remove possible leftovers from previous pihole-FTL processes
#rm -f /dev/shm/FTL-* 2> /dev/null
#rm /var/run/pihole/FTL.sock 2> /dev/null
## Ensure that permissions are set so that pihole-FTL can edit all necessary files
#chown pihole:pihole /run/pihole-FTL.pid /run/pihole-FTL.port
#chown pihole:pihole /etc/pihole /etc/pihole/dhcp.leases 2> /dev/null
#chown pihole:pihole /var/log/pihole-FTL.log /var/log/pihole.log
#chmod 0644 /var/log/pihole-FTL.log /run/pihole-FTL.pid /run/pihole-FTL.port /var/log/pihole.log
#echo "nameserver 127.0.0.1" | /sbin/resolvconf -a lo.piholeFTL
