---
- name: Clone PiHole Repo
  git:
    repo: "{{ git_pihole_base_url }}"
    dest: "{{ pihole_repo_dir }}"
    version: "HEAD"

- name: Clone Web Interface Repo
  git:
    repo: "{{ git_web_interface_url }}"
    dest: "{{ web_install_directory }}"
    version: "HEAD"
  when: pihole_install_web
